### ISSUE TITLE
After accept cookies the Shop adds "force_sid"-parameter an all urls

### ISSUE THREAD

**Issue by AlexHupe** [aggrosoft/oxid-cookie-compliance#7]
Hi, 

is the parameter necessary or is there an error in my configuration?

Thank you!

Alex

**Comment by aggrosoft** [comment]
There is no reason for that coming from the module itself, force_sid is added by oxid eShop whenever it thinks that the cookie based solution will not work (switching domains e.g. multi-language or ssl domain). The only thing that happens when you click that button is that some cookies are set and a location.reload is issued. See:

https://github.com/aggrosoft/oxid-cookie-compliance/blob/master/src/js/agcookiecompliance.js#L4-L33

I have not experienced this yet, let me know if you can add any input on when and where this happens - maybe I can find out whats happening
